# Generated by Django 5.0.4 on 2024-04-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id_anime', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TV', 'TV'), ('OVA', 'OVA'), ('Movie', 'Movie'), ('Special', 'Special'), ('ONA', 'ONA'), ('Music', 'Music')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('alternative_title', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('ranked', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('description', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mecha', 'Mecha'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Slice of Life', 'Slice of Life'), ('Sports', 'Sports'), ('Supernatural', 'Supernatural'), ('Thriller', 'Thriller'), ('Psychological', 'Psychological'), ('Adventure', 'Adventure'), ('Historical', 'Historical'), ('Magic', 'Magic'), ('Military', 'Military'), ('Music', 'Music'), ('Parody', 'Parody'), ('School', 'School'), ('Shoujo', 'Shoujo'), ('Shounen', 'Shounen'), ('Space', 'Space'), ('Super Power', 'Super Power'), ('Vampire', 'Vampire'), ('Yaoi', 'Yaoi'), ('Yuri', 'Yuri'), ('Harem', 'Harem'), ('Josei', 'Josei'), ('Demons', 'Demons'), ('Game', 'Game'), ('Police', 'Police'), ('Samurai', 'Samurai'), ('Seinen', 'Seinen'), ('Shoujo Ai', 'Shoujo Ai'), ('Shounen Ai', 'Shounen Ai'), ('Kids', 'Kids')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenres',
            fields=[
                ('id_anime_genre', models.AutoField(primary_key=True, serialize=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
        migrations.CreateModel(
            name='UsersAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-Hold', 'On-Hold'), ('Dropped', 'Dropped'), ('Plan to Watch', 'Plan to Watch')], max_length=20)),
                ('score', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
