# Generated by Django 5.0.4 on 2024-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Finished Airing', 'Finished Airing'), ('Currently Airing', 'Currently Airing'), ('Not yet aired', 'Not yet aired')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
