# Generated by Django 5.0.4 on 2024-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anime_genre_animegenres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='change me', max_length=200, null=True, verbose_name='Biography'),
        ),
    ]
