# Generated by Django 5.0.4 on 2024-04-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-Hold', 'On-Hold'), ('Dropped', 'Dropped'), ('Plan to Watch', 'Plan to Watch')], max_length=20)),
                ('score', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
