# Generated by Django 5.0.4 on 2024-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usersanime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanime',
            name='score',
            field=models.CharField(choices=[('1', 'Bad'), ('2', 'Boring'), ('3', 'Ok'), ('4', 'Very good'), ('5', 'Excellent'), ('6', 'Masterpiece')], max_length=20),
        ),
    ]
