# Generated by Django 5.0.6 on 2024-05-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usersanime_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeReviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=1000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
