# Generated by Django 5.0.6 on 2024-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_anime_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animegenres',
            name='id_anime_genre',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
