# Generated by Django 5.0.6 on 2024-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_animegenres_id_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animegenres',
            name='id_anime_genre',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
