# Generated by Django 5.0.4 on 2024-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usersanime_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanime',
            name='score',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Bad'), ('2', 'Boring'), ('3', 'Ok'), ('4', 'Very good'), ('5', 'Excellent'), ('6', 'Masterpiece')], max_length=20),
        ),
    ]
