# Generated by Django 5.0.6 on 2024-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_anime_popularity_remove_anime_ranked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
