# Generated by Django 5.0.6 on 2024-05-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
