# Generated by Django 5.0.6 on 2024-05-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user__is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
