# Generated by Django 5.0.6 on 2024-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_characters_img_url_alter_voiceactor_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='img_url',
        ),
        migrations.AddField(
            model_name='characters',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='character_img/'),
        ),
    ]
