# Generated by Django 5.0.6 on 2024-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_characters_img_url_characters_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceactor',
            name='img_url',
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='actors_img/'),
        ),
    ]
