# Generated by Django 5.0.6 on 2024-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_voiceactor_img_url_voiceactor_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='anime',
        ),
        migrations.AddField(
            model_name='characters',
            name='anime',
            field=models.ManyToManyField(related_name='characters', to='api.anime'),
        ),
    ]
