# Generated by Django 5.0.6 on 2024-05-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_voiceactor_characters_characters_voice_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='voice_actor',
            new_name='voice_actors',
        ),
    ]
